# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import voice_pb2 as voice__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in voice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VoiceServiceStub(object):
    """Voice AI Service - Complete STT, TTS, and Conversation handling
    ===== STT (Speech-to-Text) =====
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTranscribe = channel.stream_stream(
                '/voice.VoiceService/StreamTranscribe',
                request_serializer=voice__pb2.AudioChunk.SerializeToString,
                response_deserializer=voice__pb2.TranscriptChunk.FromString,
                _registered_method=True)
        self.TranscribeAudio = channel.unary_unary(
                '/voice.VoiceService/TranscribeAudio',
                request_serializer=voice__pb2.AudioRequest.SerializeToString,
                response_deserializer=voice__pb2.TranscriptResponse.FromString,
                _registered_method=True)
        self.Synthesize = channel.unary_unary(
                '/voice.VoiceService/Synthesize',
                request_serializer=voice__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=voice__pb2.AudioResponse.FromString,
                _registered_method=True)
        self.StreamSynthesize = channel.unary_stream(
                '/voice.VoiceService/StreamSynthesize',
                request_serializer=voice__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=voice__pb2.AudioChunk.FromString,
                _registered_method=True)
        self.Converse = channel.stream_stream(
                '/voice.VoiceService/Converse',
                request_serializer=voice__pb2.AudioChunk.SerializeToString,
                response_deserializer=voice__pb2.ConversationResponse.FromString,
                _registered_method=True)


class VoiceServiceServicer(object):
    """Voice AI Service - Complete STT, TTS, and Conversation handling
    ===== STT (Speech-to-Text) =====
    """

    def StreamTranscribe(self, request_iterator, context):
        """Bidirectional streaming for real-time transcription
        Client sends audio chunks, server streams back transcription results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TranscribeAudio(self, request, context):
        """Single audio file transcription (HTTP alternative)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Synthesize(self, request, context):
        """===== TTS (Text-to-Speech) =====

        Single text-to-speech synthesis
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSynthesize(self, request, context):
        """Stream synthesized speech (sentence by sentence for lower latency)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Converse(self, request_iterator, context):
        """===== Complete Conversation Flow =====

        Full conversation: User speaks → STT → LLM → TTS → User hears
        Bidirectional streaming for real-time voice conversation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTranscribe': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTranscribe,
                    request_deserializer=voice__pb2.AudioChunk.FromString,
                    response_serializer=voice__pb2.TranscriptChunk.SerializeToString,
            ),
            'TranscribeAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.TranscribeAudio,
                    request_deserializer=voice__pb2.AudioRequest.FromString,
                    response_serializer=voice__pb2.TranscriptResponse.SerializeToString,
            ),
            'Synthesize': grpc.unary_unary_rpc_method_handler(
                    servicer.Synthesize,
                    request_deserializer=voice__pb2.SynthesizeRequest.FromString,
                    response_serializer=voice__pb2.AudioResponse.SerializeToString,
            ),
            'StreamSynthesize': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSynthesize,
                    request_deserializer=voice__pb2.SynthesizeRequest.FromString,
                    response_serializer=voice__pb2.AudioChunk.SerializeToString,
            ),
            'Converse': grpc.stream_stream_rpc_method_handler(
                    servicer.Converse,
                    request_deserializer=voice__pb2.AudioChunk.FromString,
                    response_serializer=voice__pb2.ConversationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voice.VoiceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('voice.VoiceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VoiceService(object):
    """Voice AI Service - Complete STT, TTS, and Conversation handling
    ===== STT (Speech-to-Text) =====
    """

    @staticmethod
    def StreamTranscribe(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/voice.VoiceService/StreamTranscribe',
            voice__pb2.AudioChunk.SerializeToString,
            voice__pb2.TranscriptChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TranscribeAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voice.VoiceService/TranscribeAudio',
            voice__pb2.AudioRequest.SerializeToString,
            voice__pb2.TranscriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Synthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voice.VoiceService/Synthesize',
            voice__pb2.SynthesizeRequest.SerializeToString,
            voice__pb2.AudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSynthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/voice.VoiceService/StreamSynthesize',
            voice__pb2.SynthesizeRequest.SerializeToString,
            voice__pb2.AudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Converse(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/voice.VoiceService/Converse',
            voice__pb2.AudioChunk.SerializeToString,
            voice__pb2.ConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HealthServiceStub(object):
    """============================================
    Health Check
    ============================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/voice.HealthService/Check',
                request_serializer=voice__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=voice__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class HealthServiceServicer(object):
    """============================================
    Health Check
    ============================================

    """

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=voice__pb2.HealthCheckRequest.FromString,
                    response_serializer=voice__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voice.HealthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('voice.HealthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealthService(object):
    """============================================
    Health Check
    ============================================

    """

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voice.HealthService/Check',
            voice__pb2.HealthCheckRequest.SerializeToString,
            voice__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
